spring.application.name=code1

spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.url=jdbc:h2:file:./db
spring.datasource.username=Sunny
spring.datasource.password=@sunn



